# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Email.create! object: "Lorem ipsum dolor sit amet", body: "Consectetur adipiscing elit. Sed ultricies placerat augue sollicitudin sollicitudin. Donec facilisis velit at porttitor ultrices. Mauris vestibulum justo non orci aliquam pulvinar. In hac habitasse platea dictumst. Maecenas vitae felis quis felis aliquam viverra. Sed vitae pellentesque magna, quis ornare dolor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu nulla quam. Suspendisse vel arcu a nunc ullamcorper finibus. In tincidunt, ex in vestibulum mollis, dui mi euismod quam, vitae finibus leo magna ac nunc. Vivamus tincidunt pellentesque augue, sit amet laoreet arcu elementum iaculis. Phasellus efficitur mi ac odio imperdiet egestas. Duis blandit euismod nisl non mattis. Proin a leo a justo dignissim venenatis ac eget magna."
Email.create! object: "Sed nec erat orci", body: "Duis ornare porttitor massa, ac mattis erat feugiat imperdiet. Suspendisse eu laoreet tellus. Vivamus varius arcu ac arcu facilisis faucibus. Nulla eu mauris vel tortor vulputate posuere. Sed dignissim venenatis enim, a bibendum enim. Morbi auctor felis sit amet orci lobortis, quis volutpat arcu ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum porttitor tellus sem, vitae fringilla tortor mollis a. Praesent sit amet volutpat dui. Nunc sit amet enim suscipit, aliquet nulla sed, lobortis ex. Aliquam erat volutpat."
Email.create! object: "Phasellus blandit nunc in vulputate finibus", body: "Nam non ipsum non magna fringilla placerat sit amet eu orci. Mauris maximus nec ligula eu finibus. Curabitur convallis dictum eleifend. Pellentesque eget sapien sodales nisi cursus dictum. Quisque rhoncus ex a lectus ultricies, a molestie augue consectetur. Cras finibus tempus dictum. Pellentesque bibendum euismod pulvinar. Donec gravida dui a mattis fringilla. Curabitur purus nunc, convallis quis tristique sed, interdum et sem. Fusce blandit orci enim, non sagittis metus interdum ac. Nulla interdum vehicula odio at pretium. Aenean interdum risus et tincidunt eleifend."
Email.create! object: "Mauris ante felis", body: "Fermentum non aliquam eget, consequat sit amet felis. Nam at dolor a elit placerat sollicitudin. Duis suscipit quis metus at suscipit. Fusce euismod, leo eu congue pretium, metus ipsum dapibus enim, id consequat elit nisi fringilla eros. Integer finibus urna in nulla viverra, eu ullamcorper elit consectetur. Ut eget odio non libero rhoncus tincidunt sit amet vitae mauris. Aenean eu quam dignissim, ultrices nisl in, maximus justo. Duis bibendum, erat non semper malesuada, urna metus congue sapien, sollicitudin pharetra lacus nulla mattis magna. Nulla ac ornare massa. Maecenas imperdiet dapibus arcu, in consectetur arcu ornare ac. Integer massa nunc, rutrum in tempus non, fermentum eget neque. Duis iaculis eros justo, eu finibus mi imperdiet sit amet. Nunc id orci sit amet risus lobortis efficitur. Ut mattis ligula eget mauris feugiat, sed mattis lectus maximus. Cras id condimentum elit. Fusce mollis feugiat dolor sit amet lobortis."
